warning_threshold: 150

only_rules: # Only the rules specified in this list will be enabled. Cannot be specified alongside
  - mark
  - line_length
  - opening_brace
  - implicit_return
  - control_statement
  - trailing_newline
  - switch_case_alignment
  - switch_case_on_newline
  - colon
  - comma
  - operator_usage_whitespace
  - operator_whitespace
  - identifier_name
  - type_name
  - generic_type_name
  - void_return
  - force_unwrapping
  - private_over_fileprivate
  - force_try
  - force_cast
  - implicitly_unwrapped_optional
  - class_delegate_protocol
  - empty_enum_arguments
  - unneeded_break_in_switch
  - redundant_type_annotation
  - modifier_order
  - redundant_set_access_control
  - unowned_variable_capture
  - duplicate_imports
  - closure_end_indentation
  - collection_alignment
  - empty_string
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - yoda_condition
  - unused_import
  - unused_optional_binding
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_declaration
  - function_body_length
  - nesting
  - type_body_length
  - file_length
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - vendor
  - Pods
  - SuperApp/*Tests
  - SuperApp/**/*Tests
included: # Включаем только файлы с расширением .swift
  - "**/*.swift"

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 140
function_body_length:
  warning: 60
  error: 120
# they can set both implicitly with an array
type_body_length:
  - 600 # warning
  - 900 # error
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: # warning and error
    warning: 3
    error: 2
  max_length: 50 # only error
  excluded: # excluded via string array
    - iPhone
    - Row
    - Top
    - App
    - Tab
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - x
    - y
    - i
    - it
    - id
    - ID
    - to
    - up
    - URL
    - by
nesting:
  type_level:
    warning: 2
